[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
publish = false

[workspace.dependencies]
fr_core = { version = "0.1.0", path = "crates/fr_core" }
fr_window = { version = "0.1.0", path = "crates/fr_window" }
fr_render = { version = "0.1.0", path = "crates/fr_render" }
fr_ui = { version = "0.1.0", path = "crates/fr_ui" }
fr_assets = { version = "0.1.0", path = "crates/fr_assets" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing_docs_in_private_items = "warn"
undocumented_unsafe_blocks = "warn"
allow_attributes_without_reason = "warn"
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
unwrap_used = "warn"
expect_used = "warn"
