[package]
name = "fr_window"
description = "The winit window and event loop of the forge engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fr_input.workspace = true
raw-window-handle = "0.6.2"
winit = "0.30.13"
